version: "3.9"

services:
  postgres:
    container_name: virail-env-server.postgres
    hostname: postgres
    image: postgis/postgis:13-master
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  directus:
    container_name: virail-env-server.directus
    hostname: directus
    image: directus/directus:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${DIRECTUS_LISTEN:-8055}:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: ${DIRECTUS_DB_CLIENT:-pg}
      DB_HOST: ${DIRECTUS_DB_HOST:-postgres}
      DB_PORT: ${DIRECTUS_DB_PORT:-postgres}
      DB_DATABASE: ${DIRECTUS_DB_DATABASE:-postgres}
      DB_USER: ${DIRECTUS_DB_USER:-postgres}
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD:-postgres}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-d1r3ctu5}
      AUTH_PROVIDERS: ${DIRECTUS_AUTH_PROVIDERS}
      AUTH_GOOGLE_DRIVER: ${DIRECTUS_AUTH_GOOGLE_DRIVER:-openid}
      AUTH_GOOGLE_CLIENT_ID: ${DIRECTUS_AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${DIRECTUS_AUTH_GOOGLE_CLIENT_SECRET}
      AUTH_GOOGLE_ISSUER_URL: ${DIRECTUS_AUTH_GOOGLE_ISSUER_URL}
      AUTH_GOOGLE_ICON: ${DIRECTUS_AUTH_GOOGLE_ICON:-google}
      AUTH_GOOGLE_IDENTIFIER_KEY: ${DIRECTUS_AUTH_GOOGLE_IDENTIFIER_KEY:-email}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  node:
    profiles: [ "production" ]
    container_name: virail-env-server.node
    hostname: node
    build: .
    depends_on:
      directus:
        condition: service_started
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules/
    working_dir: /app
    command: node ./index.js
    env_file:
      - .env
    ports:
      - ${EXPRESS_LISTEN:-3000}:3000
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  varnish:
    profiles: [ "production" ]
    container_name: virail-env-server.varnish
    hostname: varnish
    image: darioguarascio/varnish-elk-docker:latest
    restart: unless-stopped
    depends_on:
      node:
        condition: service_started
    volumes:
      - /vcache
      - ./config/varnish/varnish_backends.vcl:/usr/share/varnish/vcl/varnish_backends.vcl
    ports:
      - ${VARNISH_LISTEN:-80}:80
    environment:
      ENV: ${VARNISH_ENV:-dev}
      VARNISHD_MEMORY: ${VARNISH_MEMORY:-malloc,32m}
      VARNISH_PURGE_KEY: ${VARNISH_PURGE_KEY:-dev}
    healthcheck:
      test: [ "CMD", "sh", "-c", "test -e /proc/`cat /varnish.pid` || (kill -s 15 -1 && (sleep 10; kill -s 9 -1))" ]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 5s
    logging:
      driver: syslog
      options:
        cache-disabled: "false"
        syslog-address: udp://${VARNISH_LOGGER_IP:-127.0.0.1}:${VARNISH_LOGGER_PORT:-5445}