version: "3.5"

services:
  postgres:
    container_name: virail-env-server.postgres
    image: postgis/postgis:13-master
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  directus:
    container_name: virail-env-server.directus
    image: directus/directus:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${DIRECTUS_LISTEN}:8055"
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: ${DIRECTUS_DB_CLIENT}
      DB_HOST: ${DIRECTUS_DB_HOST}
      DB_PORT: ${DIRECTUS_DB_PORT}
      DB_DATABASE: ${DIRECTUS_DB_DATABASE}
      DB_USER: ${DIRECTUS_DB_USER}
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  node:
    container_name: virail-env-server.node
    build: .
    depends_on:
      - directus
    restart: unless-stopped
    hostname: node
    volumes:
      - .:/app
      - /app/node_modules/
    working_dir: /app
    command: node ./index.js
    env_file:
      - .env
    ports:
      - "${EXPRESS_LISTEN}:3000"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}